/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ILHAM
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dokter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        negara = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        spesialis = new javax.swing.JTextField();
        goldar = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        Identitas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PEMILIHAN DOKTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 250, 60);

        jLabel2.setText("Dokter Spesialis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 510, 120, 30);

        dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu", "DR. Ilham", "DR. Jalu", "DR. Prakosa" }));
        dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterActionPerformed(evt);
            }
        });
        getContentPane().add(dokter);
        dokter.setBounds(140, 110, 170, 20);

        jLabel3.setText("PILIH DOKTER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 90, 20);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 190, 70, 30);

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 230, 70, 30);

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 310, 110, 30);

        jLabel8.setText("Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 390, 70, 30);

        jLabel9.setText("Usia");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 270, 70, 30);

        jLabel10.setText("Golongan Darah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 350, 120, 30);

        jLabel11.setText("Waktu Praktek");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 470, 100, 30);

        jLabel12.setText("Kewarganegaraan");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 430, 130, 30);
        getContentPane().add(negara);
        negara.setBounds(200, 430, 170, 30);

        nama.setEditable(false);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(200, 190, 170, 30);
        getContentPane().add(spesialis);
        spesialis.setBounds(200, 510, 170, 30);
        getContentPane().add(goldar);
        goldar.setBounds(200, 350, 170, 30);
        getContentPane().add(waktu);
        waktu.setBounds(200, 470, 170, 30);
        getContentPane().add(alamat);
        alamat.setBounds(200, 230, 170, 30);
        getContentPane().add(jk);
        jk.setBounds(200, 310, 170, 30);
        getContentPane().add(usia);
        usia.setBounds(200, 270, 170, 30);
        getContentPane().add(status);
        status.setBounds(200, 390, 170, 30);

        Identitas.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        Identitas.setLayout(null);
        getContentPane().add(Identitas);
        Identitas.setBounds(20, 150, 360, 430);

        setBounds(0, 0, 416, 627);
    }// </editor-fold>//GEN-END:initComponents

    private void dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterActionPerformed
    // TODO add your handling code here:
    if(dokter.getSelectedItem().equals("DR. Ilham")){
    nama.setText("DR. Ilham");
    alamat.setText("Jl. Surabaya 16, Malang");
    usia.setText("20 Tahun");
    jk.setText("Laki-Laki");
    goldar.setText("A");
    status.setText("Belum Menikah");
    negara.setText("London");
    spesialis.setText("Dokter Umum");
    waktu.setText("Pagi (07.00 - 15.00)");}
    
    else if(dokter.getSelectedItem().equals("DR. Jalu")){
    nama.setText("DR. Jalu");
    alamat.setText("Jl. Veteran 3, Malang");
    usia.setText("20 Tahun");
    jk.setText("Perempuan");
    goldar.setText("O");
    status.setText("Belum Menikah");
    negara.setText("Australia");
    spesialis.setText("Dokter Gigi");
    waktu.setText("Pagi (16.00 - 22.00)");}
    
    else if(dokter.getSelectedItem().equals("DR. Prakosa")){
    nama.setText("DR. Prakosa");
    alamat.setText("Jl. Bandung 9, Malang");
    usia.setText("20 Tahun");
    jk.setText("Laki-Laki");
    goldar.setText("O");
    status.setText("Belum Menikah");
    negara.setText("Amerika");
    spesialis.setText("Dokter Saraf");
    waktu.setText("Pagi (22.00 - 06.00)");}
    }//GEN-LAST:event_dokterActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Identitas;
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> dokter;
    private javax.swing.JTextField goldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField negara;
    private javax.swing.JTextField spesialis;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
